### ISSUE TITLE
Support for React 16?

### ISSUE THREAD

**Issue by samfattah** [rico345100/react-multimedia-capture#1]

**Comment by rico345100** [comment]
Looks like this doesn't work with React 16. Thank you for reporting, I'll check this soon!

**Comment by rico345100** [comment]
Sorry for late answer, I was little busy these days. Anyway I just tried to use this module with react-16 and it fails with bunch of errors. This errors coming from new react-dom module, but I didn't used any version specific-things, so it might be glitch that I can't fix.

I think this will resolve after new version released but I will ask this and try to fix this as possible as I can.

**Comment by rico345100** [comment]
I just updated this module to support React 16, it works now!
Don't forget to update @1.1.0! Enjoy it and don't forget the star :)
