### ISSUE TITLE
Preview image before record?

### ISSUE THREAD

**Issue by fedeevilla** [rico345100/react-multimedia-capture#12]
Hello, I have a question!

Is there any possibility to preview the image before record? I don't know how do it.

**Comment by rico345100** [comment]
Maybe this will help: https://developer.mozilla.org/en-US/docs/Web/API/MediaStream_Image_Capture_API

However it's could be not part of this module.

**Comment by fedeevilla** [comment]
Hello, thanks, but why not? It is important to preview an image before recording..

I tried with this but fails on close. Webcam's Led isn't turn off. Do you have any idea? Thanks again.

**Comment by rico345100** [comment]
Well, that could be important but taking snapshot of mediastream is not part of this module.

**Comment by fedeevilla** [comment]
I think I don't explain this well. Is there any way to show webcam without record?

**Comment by rico345100** [comment]
When you grant camera access from browser, Webcam will work immediately. Also when it's granted, stream is passed to onGranted function prop. Maybe you can convert stream as screenshot as I mentioned above.

**Comment by rico345100** [comment]
Any progress? If you solved the problem, please close this issue. If you still stuck in this problem, I'll check this when I get back to home.
