### ISSUE TITLE
how to access handleStart outside of MediaCapture.

### ISSUE THREAD

**Issue by sravanshty** [rico345100/react-multimedia-capture#6]
Hello,

As per the code we can access onStart={this.handleStart}......render = ({ start...}). But i just wanted to invoke handleStart function outside of <MediaCapture>. Like in some button click i just wanted to invoke. Could you please help me out this solution.

Thanks,
Sravan Kumar Shetty

**Comment by rico345100** [comment]
Hello.

To access internal method in class, you can make external reference something like this:

```javascript
let handleStartRef;

class SomeComponent extends Component {
    constructor() {
        handleStartRef = this.handleStart;
    }
    handleStart = () => {
        // ...
    }
    ...
}

// Outside of SomeComponent
// Make sure that at least one object instantiated SomeComponent constructor(class)
document.getElementById("some-button").onclick = function() {
    if(typeof handleStartRef === "undefined") return;
    handleStartRef();        // Invoke SomeComponent::handleStart
}
```

I won't sure the code works because it's just pseudo code, however this kind of approach will works because I already used some react apps.

**Comment by rico345100** [comment]
I'm closing this, if you have any issue, you can freely re-open this.
